routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
    Route::get('login', array('as' => 'auth-login', 'uses' => 'AuthController@login'));
    Route::post('postlogin', array('as' => 'auth-post-login', 'uses' => 'AuthController@postLogin'));
    Route::get('logout', array('as' => 'logout', 'uses' => 'AuthController@logout'));
});

Route::group(['prefix' => 'admin','middleware' => 'SentinelHasAccess:administrator', 'namespace' => 'Admin'], function () {

    Route::get('dashboard', array('as' => 'admin-dashboard', 'uses' => 'DashboardController@index'));

    // Route::group(['prefix' => 'management'], function () {

        Route::resource('/corporate-identity','CorporateIdentityController',
        [
            'names' => 'admin.corporate-identity',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/team','TeamController',
        [
            'names' => 'admin.team',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/contact','ContactController',
        [
            'names' => 'admin.contact',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/service','ServiceController',
        [
            'names' => 'admin.service',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/service-list','ServiceListController',
        [
            'names' => 'admin.service-list',
            'except' => [
                'show',
            ],
        ]);
        Route::resource('/our-client','OurClientController',
        [
            'names' => 'admin.client',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/career','CareerController',
        [
            'names' => 'admin.career',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/milestone','MilestoneController',
        [
            'names' => 'admin.milestone',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/compliance-and-governance','ComplianceGovernanceController',
        [
            'names' => 'admin.compliance',
            'except' => [
                'show',
            ],
        ]);

        Route::get('/compliance-and-governance/cgc', array('as' => 'admin.cgc.index', 'uses' => 'ComplianceController@cgc'));
        Route::get('/compliance-and-governance/cgc/update', array('as' => 'admin.cgc.update', 'uses' => 'ComplianceController@cgcUpdate'));
        Route::post('/compliance-and-governance/cgc/store', array('as' => 'admin.cgc.store', 'uses' => 'ComplianceController@cgcStore'));

        Route::get('/compliance-and-governance/hse', array('as' => 'admin.hse.index', 'uses' => 'ComplianceController@hse'));
        Route::get('/compliance-and-governance/hse/update', array('as' => 'admin.hse.update', 'uses' => 'ComplianceController@hseUpdate'));
        Route::post('/compliance-and-governance/hse/store', array('as' => 'admin.hse.store', 'uses' => 'ComplianceController@hseStore'));

        Route::post('/compliance-and-governance/create', array('as' => 'create-csr', 'uses' => 'CsrController@storeDesc'));
        Route::get('/charter-of-commitees', array('as' => 'admin.charter.index', 'uses' => 'ComplianceController@login'));

        Route::resource('/compliance-and-governance/charter','CharterController',
        [
            'names' => 'admin.charter',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/compliance-and-governance/csr','CsrController',
        [
            'names' => 'admin.csr',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/investor-relation','InvestorRelationController',
        [
            'names' => 'admin.investor',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/image-header','ImageHeaderController',
        [
            'names' => 'admin.image-header',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/investor-relation/financial-highlights','FinancialHighlightController',
        [
            'names' => 'admin.financial',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/investor-relation/annual-reports','AnnualReportController',
        [
            'names' => 'admin.annual',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/investor-relation/investor-calendars','InvestorCalendarController',
        [
            'names' => 'admin.calendar',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/investor-relation/shareholders','ShareholderController',
        [
            'names' => 'admin.shareholder',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/investor-relation/shareholder-compo','ShareholderCompoController',
        [
            'names' => 'admin.shareholder-composition',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/news/corporate-action','CorporateActionController',
        [
            'names' => 'admin.corporate-action',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/news/media-clipping','MediaClippingController',
        [
            'names' => 'admin.media-clipping',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/news/media-center','MediaCenterController',
        [
            'names' => 'admin.media-center',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/file-manager','FileManagerController',
        [
            'names' => 'admin.filemanager',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/footer','FooterController',
        [
            'names' => 'admin.footer',
            'except' => [
                'show',
            ],
        ]);

        Route::resource('/company-with-tram','CompanyWithTramController',
        [
            'names' => 'admin.company',
            'except' => [
                'show',
            ],
        ]);

    // });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {

  return view('frontend.index');

});
Route::get('/admin-login', function () {
	$form = [
        'url' => route('auth-post-login'),
        'autocomplete' => 'off',
    ];
    return view('backend.auth.login', compact('form'));
});
Route::get('/home', array('as' => 'home', 'uses' => 'HomeController@home'));
Route::get('/about', array('as' => 'about', 'uses' => 'HomeController@about'));
Route::get('/milestone', array('as' => 'milestone', 'uses' => 'HomeController@milestone'));
Route::get('/services', array('as' => 'services', 'uses' => 'HomeController@services'));
Route::get('/careers', array('as' => 'careers', 'uses' => 'HomeController@careers'));
Route::get('/compliance', array('as' => 'compliance', 'uses' => 'HomeController@compliance'));
Route::get('/investor-relations', array('as' => 'investor-relation', 'uses' => 'HomeController@investor'));
Route::get('/investor-relation/financial-highlights', array('as' => 'financial-highlight', 'uses' => 'HomeController@financial'));
Route::get('/investor-relation/annual-reports', array('as' => 'annual-report', 'uses' => 'HomeController@annual'));
Route::get('/investor-relation/investor-calendar', array('as' => 'investor-calendar', 'uses' => 'HomeController@investorCalendar'));
Route::get('/investor-relation/shareholder-info', array('as' => 'shareholder-info', 'uses' => 'HomeController@shareholderInfo'));
Route::get('/investor-relation/shareholder-composition', array('as' => 'shareholder-compo', 'uses' => 'HomeController@shareholderCompo'));
Route::get('/news/corporate-year', array('as' => 'corporate-year', 'uses' => 'HomeController@corporateYear'));
Route::get('/news/media-clipping', array('as' => 'media-clipping', 'uses' => 'HomeController@mediaClipping'));
Route::get('/news/media-center', array('as' => 'media-center', 'uses' => 'HomeController@mediaCenter'));
Route::get('/contact-us', array('as' => 'contact-us', 'uses' => 'HomeController@contact'));
Route::get('/service-cate/{id}', array('as' => 'service-cate', 'uses' => 'HomeController@serviceCate'));

app/Http/Controllers/Admin/OurClientController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\DataTables\OurClientDataTable;
use App\Http\Controllers\Controller;
use App\Models\Client;

class OurClientController extends Controller
{
  public function index(Request $req, OurClientDataTable $dataTable)
  {
      $param = $req->all();

      if (array_key_exists('message', $param)) {
          flash()->success($param['message']);
          return $dataTable->render('backend.our_clients.index');
      } else {
          return $dataTable->render('backend.our_clients.index');
      }
  }

  public function create()
  {
      return view('backend.our_clients.create');
  }

  public function store(Request $request)
  {
      $param = $request->except('_token');
      // dd($param);
      $client = New Client;
      $client->name = $param['name'];

      if (@$param['image']) {
        $uploadImage = upload_file($param['image'], 'uploads/our_clients/');
        $client->image = $uploadImage['original'];
      }
      $client->save();

      if (!empty($client)) {
          $request->session()->flash('success', 'Client added successfully!');
          return redirect()->route('admin.client.index');
      } else {
          $request->session()->flash('error', 'Client added to created!');
          return redirect()->route('admin.client.index');
      }
  }

  public function edit($id)
  {
      $data = Client::findOrFail($id);

      if (!empty($data)) {
          return view('backend.our_clients.edit')->withData($data);
      } else {
          session()->flash('error', 'Data not found!');
          return redirect()->route('admin.client.index');
      }
  }

  public function update(Request $request, $id)
  {
      $param = $request->except('_token');
      $updateData = Client::findOrFail($id);
      if($file = $request->hasFile('image')) {
            $file = $request->file('image');
            $filename = time() . '.' . $file->getClientOriginalExtension();
            $destinationPath = public_path() . '/uploads/our_clients/';
            $file->move($destinationPath, $filename);
            $updateData->image = 'uploads/our_clients/'.$filename;
      }
      $updateData->name = $param['name'];
      $updateData->update();

      if (!empty($updateData)) {
          $request->session()->flash('success', 'Client updated successfully!');
          return redirect()->route('admin.client.index');
      } else {
          $request->session()->flash('error', 'Client failed to updated!');
          return redirect()->route('admin.client.index');
      }

  }

  public function destroy($id)
    {
      if (!empty($id)) {
          $deleteData = Client::findOrFail($id);
          $deleteData->delete();

          if ($deleteData != false) {
              session()->flash('success', 'Client successfully deleted!');
              return redirect()->route('admin.client.index');
          } else {
              session()->flash('error', 'Client failed deleted!');
              return redirect()->route('admin.client.index');
          }
      } else {
          $request->session()->flash('error', 'Client not found!');
              return redirect()->route('admin.client.index');
      }
    }
}

resources/views/backend/our_clients/_form.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
    {!! Form::label('name', "Name", ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-5">
        {!! Form::text('name', old('name') , ['class' => 'form-control']) !!}
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('image') ? 'has-error' : ''}}">
    {!! Form::label('image', trans('Image / Icon'), ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-6">
      <div class="fileinput fileinput-new" data-provides="fileinput">
          <div class="fileinput-new thumbnail" style="width: 200px; height: auto;">
              <img id="imageBrand" src="{{(@$data->image) ? get_file($data->image, 'original') : url('images/noimagefound.jpg')}}">
          </div>
          <div>
              <span class="btn btn-default btn-file">
                  <span class="fileinput-new">Choose Image</span>
                  <input type="file" accept="image/jpg, image/png" name="image" id="brandImage"  value="{{@$data->image}}">
              </span>
          </div>
      </div>
    </div>
</div>

resources/views/backend/our_clients/create.blade.php
@extends('backend.layouts.master.master')

@section('title')
    Our Client - {{ trans('general.create_new') }}
@endsection

@section('page-header')
    Our Client
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li><a href="{!! route('admin-dashboard') !!}"><i class="fa fa-hashtag"></i> Home</a></li>
        <li class="active">{{ trans('general.create_new') }} Our Client</li>
    </ol>
@endsection

@section('content')
    {!! Form::open([
            'route' =>  'admin.client.store',
            'class' =>  'form-horizontal',
            'id'    =>  'form-user',
            'enctype' => 'multipart/form-data',
        ]) !!}
        <div class="box box-primary" style="margin-top: 20px" >
            @if(Session::has('success'))
                <div class="alert alert-success"><em> {!! session('success') !!}</em></div>
            @endif
            @if(Session::has('error'))
                <div class="alert alert-error"><em> {!! session('error') !!}</em></div>
            @endif
            {{-- <div class="box-header with-border">
               <h3 class="box-title">Ajukian Cuti Baru</h3>
            </div> --}}
            <div class="box-body">
                @include('backend.our_clients._form')
                <div class="form-group pull-right">
                    <div class="col-sm-12">
                        <a href="{!! route('admin-dashboard') !!}" class="btn btn-danger">Cancel</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection
@section('scripts')
  <script>
  $(document).ready(function() {
      // $('#about_us').summernote({
      //   tabsize: 2,
      //   height: 200
      // });
      //
      // $('#address').summernote({
      //   tabsize: 2,
      //   height: 200
      // });
      //
      // $('#legal_of_bussiness1').summernote({
      //   tabsize: 2,
      //   height: 200
      // });

      $('.textarea').wysihtml5();
  });
  </script>

@endsection

resources/views/backend/our_clients/edit.blade.php
@extends('backend.layouts.master.master')

@section('title')
    Our Client - {{ trans('general.edit') }}
@endsection

@section('page-header')
    Our Client <small>{{trans('general.edit')}}</small>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li><a href="{!! route('admin-dashboard') !!}"><i class="fa fa-hashtag"></i> Home</a></li>
        <li><a href="{!! route('admin.client.index') !!}">Our Client {{ trans('general.management') }}</a></li>
        <li class="active">{{ trans('general.edit') }}</li>
    </ol>
@endsection

@section('content')

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body">
            {!! Form::model($data,['route' =>['admin.client.update',$data->id],'class' =>'form-horizontal','id' => 'form-user','method' => 'PATCH', 'enctype' => 'multipart/form-data',]) !!}
            @include('backend.our_clients._form')
            <div class="row">
                <div class="col-xs-12 m-top-10 text-right">
                    <a href="{!! route('admin.client.index') !!}" class="btn btn-danger">Cancel</a>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
            {!! Form::close() !!}
            </div>
        </div>
    </div>

</div>
@endsection

@section('scripts')
  <script>
  $(document).ready(function() {
      // $('#about_us').summernote({
      //   tabsize: 2,
      //   height: 200
      // });
      //
      // $('#address').summernote({
      //   tabsize: 2,
      //   height: 200
      // });
      //
      // $('#legal_of_bussiness1').summernote({
      //   tabsize: 2,
      //   height: 200
      // });

      $('.textarea').wysihtml5();
  });
  </script>

@endsection

resources/views/backend/our_clients/index.blade.php
@extends('backend.layouts.master.master')

@section('title')
    Our Client {{ trans('general.management') }}
@endsection

@section('page-header')
    Our Client {{ trans('general.management') }}
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        {{-- <li><a href="{!! route('admin-dashboard') !!}"><i class="fa fa-map"></i> Home</a></li>
        <li class="active">{{ trans('general.list') }} {{ trans('general.users') }}</li> --}}
        <a href="{!! route('admin.client.create') !!}"><button type="button" class="btn btn-primary">+ Add Client</button></a>
    </ol>
@endsection

@section('content')
<div class="row">
  <div class="col-lg-12 col-xs-6">
    <div class="row pull-right">
      <div class="col-lg-12 col-xs-6 ">
        {{--  <a href="{{ route('suppliers.create')}}" class="btn btn-primary"> Add New </a>   --}}
      </div>
    </div>
    <div class="row" >
      <div class="col-lg-12 col-xs-6">
          <div class="box box-primary " style="margin-top: 20px">
              <div class="box-header">
                @if(Session::has('success'))
                    <div class="alert alert-success"><em> {!! session('success') !!}</em></div>
                @endif
                @if(Session::has('error'))
                    <div class="alert alert-error"><em> {!! session('error') !!}</em></div>
                @endif
              </div>
              <div class="box-body">
                  {!! $dataTable->table(['class' => 'datatable table table-striped', 'cellspacing'=>"0", 'width'=>"100%"]) !!}
              </div>
          </div>
      </div>
    </div>
</div>
@include('partials.delete-modal')
@endsection
@include('backend.our_clients.scripts.index_script')